stages:
  - deploy

deploy_staging:
  stage: deploy
  image: tetraweb/php:7.1
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$STAGING_PRIVATE_KEY")
    - apt-get install rsync
  script:
    - ssh -p22 fbndev@aries.uberspace.de "mkdir -p /var/www/virtual/fbndev/stable-version.florianbrinkmann.de/wp-content/themes/schlicht"
    - ssh -p22 fbndev@aries.uberspace.de "mkdir -p /var/www/virtual/fbndev/trunk-version.florianbrinkmann.de/wp-content/themes/schlicht"
    - rsync -rav -e ssh --exclude='.git/' --exclude='.gitlab-ci.yml' --delete-excluded ./ fbndev@aries.uberspace.de:/var/www/virtual/fbndev/trunk-version.florianbrinkmann.de/wp-content/themes/schlicht
    - rsync -rav -e ssh --exclude='.git/' --exclude='.gitlab-ci.yml' --delete-excluded ./ fbndev@aries.uberspace.de:/var/www/virtual/fbndev/stable-version.florianbrinkmann.de/wp-content/themes/schlicht
    - ssh -p22 fbndev@horologium.uberspace.de "cp -Rf /var/www/virtual/fbndev/trunk-version.florianbrinkmann.de/wp-content/themes/schlicht/ /var/www/virtual/fbndev/trunk-version.florianbrinkmann.de/wp-content/themes-for-docblock-parser/schlicht/"
    - ssh -p22 fbndev@horologium.uberspace.de "cp -Rf /var/www/virtual/fbndev/stable-version.florianbrinkmann.de/wp-content/themes/schlicht/ /var/www/virtual/fbndev/stable-version.florianbrinkmann.de/wp-content/themes-for-docblock-parser/schlicht/"
  environment:
    name: staging
  only:
    - staging

deploy_production:
  stage: deploy
  image: tetraweb/php:7.1
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$STAGING_PRIVATE_KEY")
    - apt-get install rsync zip
  script:
    - ssh -p22 fbn@horologium.uberspace.de "mkdir -p /var/www/virtual/fbn/html/wp-content/themes/_tmp-schlicht"
    - ssh -p22 fbn@horologium.uberspace.de "mkdir -p /var/www/virtual/fbn/html/wp-content/themes/schlicht"
    - rsync -rav -e ssh --exclude='.git/' --exclude='.gitlab-ci.yml' --delete-excluded ./ fbn@horologium.uberspace.de:/var/www/virtual/fbn/html/wp-content/themes/_tmp-schlicht
    - ssh -p22 fbn@horologium.uberspace.de "mv /var/www/virtual/fbn/html/wp-content/themes/schlicht /var/www/virtual/fbn/html/wp-content/themes/_old-schlicht && mv /var/www/virtual/fbn/html/wp-content/themes/_tmp-schlicht /var/www/virtual/fbn/html/wp-content/themes/schlicht"
    - ssh -p22 fbn@horologium.uberspace.de "rm -rf /var/www/virtual/fbn/html/wp-content/themes/_old-schlicht"
    - ssh -p22 fbn@horologium.uberspace.de "cp -Rf /var/www/virtual/fbn/html/wp-content/themes/schlicht/ /var/www/virtual/fbn/html/wp-content/themes-for-docblock-parser/schlicht/"
    - ssh -p22 fbn@horologium.uberspace.de "cd /var/www/virtual/fbn/html/wp-content/themes/ && zip -r schlicht.zip schlicht/"
    - ssh -p22 fbn@horologium.uberspace.de "mv /var/www/virtual/fbn/html/wp-content/themes/schlicht.zip /var/www/virtual/fbn/woocommerce-downloads/schlicht.zip"
  environment:
    name: production
  only:
    - master
